#### Lab 7: 1-way ANOVA #### 
# Clean up the working environment
rm(list = ls())
# Verify working directory, should be ~/Documents/Analyses/lastname_first
getwd()

# Install package ggfortify, *note* only do install.packages ONCE
# ggfortify is a package that works with ggplot2 to make nice plots
# install.packages("ggfortify")
library("ggfortify")
# multcomp is used for contrasts and multiple comparisons
# install.packages("multcomp")
library("multcomp")
# nlme is used for random effects ANOVA
# install.packages("nlme")
library("nlme")

# Load tidyverse
library("tidyverse")
# Check for updates
tidyverse_update()

### General workflow ####

# The general workflow as you do analyses in R should be as follows:
#   Step 1.  Plot your data (boxplots, histograms, Q-Q plots)
#   Step 2.  Use the function lm() to fit a model, specifying equation & data
#     e.g., y ~ x, data = data
#   Step 3.  Check assumptions again, using residuals plot
#   Step 4.  If assumptions are met, use the functions anova() and summary() 
#     to interpret statistical results.  If assumptions are not met, try 
#     data transformation and/or a non-parametric or robust version of the test

### Fixed effects ANOVA ####

### Step 1.  Read in and plot data ####

# I have added a new folder with datafiles located at "datasets/r4all"
daphnia <-read_csv("datasets/r4all/Daphniagrowth.csv", col_types = cols(
  parasite = col_factor() ))

# It is important to read in the predictor as a factor
# In the case of this dataset, the parasite names have a space so I recoded
# the factor levels using the function fct_recode()
daphnia <- daphnia %>%
  mutate(parasite = fct_recode(parasite, Metschnikowia = "Metschnikowia bicuspidata",
             Pansporella = "Pansporella perplexa",
             Pasteuria = "Pasteuria ramosa"
             ))

# The research question here is two-fold: Q1: whether parasites alter host growth rates, 
# Q2: whether each of the three parasites reduces growth, compared with a control, 
# no parsite treatment.  The host is Daphnia, genus of water flea.

# Look at the data
head(daphnia)
summary(daphnia)

# When you do a normal boxplot, the parasite species names overlap and are illegible
# so add a line that tells ggplot to flip the x and y axes, coord_flip()
ggplot(daphnia, aes(x = parasite, y = growth.rate))+
  geom_boxplot() +
  theme_bw() +
  coord_flip()
ggplot(daphnia) +
  geom_histogram(aes(growth.rate), binwidth = 0.1)+
  facet_wrap(~parasite)
ggplot(daphnia)+
  geom_qq(aes(sample = growth.rate, color = parasite))

### Step 2.  Construct your ANOVA ####

# Similar to our two-sample t-test, you specify an equation (y~x) and the data

model01 <- lm(growth.rate~parasite, data = daphnia)

# You will see the model01 object in your Environment tab.  If you click on the 
# blue triangle, you will see all the bits and pieces generated by the function
# lm()

### Step 3.  Check the assumptions, again ####

# You alread have a good idea about normality, based on the preliminary plots in 
# Step 1.  After the model is fitted we can check the residuals too.
# I prefer to compare the ratio of standard deviations at this point in my code,
# but you could have done it earlier if you please.

summ_growth.rate <- daphnia %>%
  group_by(parasite) %>% 
  summarise(mean_growth.rate = mean(growth.rate),
            sd_growth.rate = sd(growth.rate),
            n_growth.rate = n())
ratio <-(max(summ_growth.rate$sd_growth.rate))/(min(summ_growth.rate$sd_growth.rate))

# The function autoplot will give you a residuals by predicte plot, which is 
# called "Residuals vs. Fitted" here.  It also gives you a Q-Q plot of the RESIDUALS.

autoplot(model01)

# If it looks hideous, try clicking on the little Zoom magnifying glass to open
# the plot in a larger window.

### Step 4. Interpret results ####

# Use the function anova() to answer our first research question: is there an effect
# of parasite treatment on Daphnia growth rate?

anova(model01)

# the row beginning with our predictor variable name (parasite) shows a significant
# p<0.0001, so there is an effect of parasite treatment on growth rate.

# To address the second question, which parasites are different from the control, we
# can choose among approaches.

# Start with a summary of the model results
summary(model01)

# There are 4 rows in the table of coefficients and the first row is labeled intercept.
# Do not be fooled!  This is not the grand mean as a reasonable human might expect!
# Instead, because R alphabetized the names of your parasite treatment groups, it 
# is the mean of the control (C comes before M and P in the alphabet) group. 
# So going forward, just assume that the word '(Intercept)' represents the first 
# level of the alphabetically ordered treatment levels.  Treatment contrasts
# report differences between the reference level (in this lucky case the control)
# and the other levels.  So in the summary table the numbers associated with each
# parasite are differences between growth rates associated with that parasite and
# the control.

# Because the control ended up as the reference group, the p-values associated 
# with the contrasts are actually useful.  That said, they are totally at risk
# of elevated type I error, so you'd be better off using Tukey HSD to evaluate 
# pairwise differences!

### Multiple Comparisons ####

# Earlier you installed and loaded the package multcomp.  To do planned comparisons
# we will use a function in multcomp called glht, short for general linear
# hypotheses.
# linfct specifies the linear hypotheses to be tested, I find the easiest way
# is to specify by name

# Planned comparisons

planned <- glht(model01, linfct = 
                  mcp(parasite = c("Metschnikowia - control = 0",
                                    "Pansporella - control = 0",
                                    "Pasteuria - control = 0")))
confint(planned)
summary(planned)

# Unplanned comparisons
# The key things you need to specify here are the model name and the factor name

tukey <- glht(model01, linfct = mcp(parasite = "Tukey"))
summary(tukey)

### Multiple Comparisons if package "multcomp" fails ####
model01_b <- aov(growth.rate ~ parasite, daphnia)
TukeyHSD(model01_b)


### Non-parametric Kruskal-Wallis test ####
# This is a very simple test output, it gives you a test statistic, df, and p

kruskal.test(growth.rate ~ parasite, data = daphnia)


### Robust Welch's ANOVA ####

# I cannot tell you why the function for this is called oneway.test()
# Regardless this is how you do it:
oneway.test(growth.rate ~ parasite, data = daphnia)

### Random effects ANOVA ####
# For this, we will use the example in your book examining the repeatibility of
# measurements on walking stick limbs
stick <- read_csv("datasets/abd/chapter15/chap15e6WalkingStickFemurs.csv",
                  col_types = cols(specimen = col_factor() ) )

# To include a random effect, we no longer use the linear model function lm(),
# instead we use lme()

# The random effects ANOVA function requires two formulas, rather than just one. 
# The first formula (beginning with "fixed =") is for the fixed effect. The walking
# stick insect example doesn't include a fixed-effect variable, so we just provide
# a symbol for a constant in the formula ("~ 1"), representing the grand mean. The
# second formula (beginning with "random =") is for the random effect. In this 
# example, the individual specimens are the random groups, and the second formula
# indicates this (the "~ 1" in the formula below indicates that each specimen has 
# its own mean). You will need to have loaded the nlme library.

model02 <- lme(fixed = femurLength ~ 1,
               random = ~1|specimen, data = stick)

# Obtain the variance components for the random effects using VarCorr. The output includes
# the standard deviation and variance for both components of random variation in the random
# effects model for this example. The first is the variance among the specimen means. This 
# is the variance among groups, and is confusingly labeled "Intercept" in the output. The
# second component is the variance among measurements made on the same individuals. This 
# is the within group variance, also known as the error mean square, and is labeled 
# "Residual" in the output.

model02_varcomp <- VarCorr(model02)
model02_varcomp

# This gives us the estimates of the variance components for groups/Intercept and 
# error/Residual

# To get repeatibility, tell R to do some math by extracting the first entry in the first
# column and calling it VarAmong

varAmong  <- as.numeric( model02_varcomp[1,1] )

# And then extracting the second entry in the first column and calling it VarWithin
varWithin <- as.numeric( model02_varcomp[2,1] )

# And then doing the math
repeatability <- varAmong / (varAmong + varWithin)
repeatability

# End of story, 74% of walking stick femur length is due to variability among actual
# insects, not picture analysis issues.








